In [ ]:
# Documentación completa en https://numpy.org/doc/stable/index.html

In [3]:
import pandas as pd
url = (
    "https://raw.githubusercontent.com/JoaquinAmatRodrigo/Estadistica-machine-learning-python/"
    "master/data/SaratogaHouses.csv"
)
datos = pd.read_csv(url, sep=",")

In [4]:
# Se renombran las columnas para que sean más descriptivas
datos.columns = ["precio", "metros_totales", "antiguedad", "precio_terreno", "metros_habitables",
                 "universitarios", "dormitorios", "chimenea", "banyos", "habitaciones",
                 "calefaccion","consumo_calefacion", "desague", "vistas_lago", "nueva_construccion",
                 "aire_acondicionado"]

In [5]:
datos.head(4)

precio  metros_totales  antiguedad  precio_terreno  metros_habitables  \
0  132500            0.09          42           50000                906   
1  181115            0.92           0           22300               1953   
2  109000            0.19         133            7300               1944   
3  155000            0.41          13           18700               1944   

   universitarios  dormitorios  chimenea  banyos  habitaciones  \
0              35            2         1     1.0             5   
1              51            3         0     2.5             6   
2              51            4         1     1.0             8   
3              51            3         1     1.5             5   

       calefaccion consumo_calefacion            desague vistas_lago  \
0         electric           electric             septic          No   
1  hot water/steam                gas             septic          No   
2  hot water/steam                gas  public/commercial          No   
3          hot air                gas             septic          No   

  nueva_construccion aire_acondicionado  
0                 No                 No  
1                 No                 No  
2                 No                 No  
3                 No                 No

In [ ]:
# Crear matrices unidimensionales 
import numpy as np
miArrayUnidimensional = np.array([1,2,3,4,5,6])
miArrayUnidimensional

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Crear matrices bidimensionales 

miArrayBidimensional = np.array([['A','B','C'],['D','E','F']])
miArrayBidimensional

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [ ]:
# Crear matrices n-dimensionales 

miArrayNdimensional = np.array([[0,1],[5,6],[8,9]])
miArrayNdimensional

array([[0, 1],
       [5, 6],
       [8, 9]])

In [ ]:
# ¿Por qué usar NumPy en vez de las listas de Python?

### Uso de Memoria
import sys
numerosLista = range(1000)
print('Uso de memoria utilizado una lista:', sys.getsizeof(numerosLista[1]) * len (numerosLista))
numerosNumPy = np.arange(1000)
print('Uso de memoria utilizado numPy:', numerosNumPy.itemsize * numerosNumPy.size)

Uso de memoria utilizado una lista: 28000
Uso de memoria utilizado numPy: 8000


In [ ]:
### Simplicidad de Operaciones
tamanioLista = 1000000
lista1 = range(tamanioLista)
lista2 = range(tamanioLista)
numpy1 = np.arange(tamanioLista)
numpy2 = np.arange(tamanioLista)
suma1 = [x + y for x, y in zip(lista1, lista2)]
suma2 = numpy1 + numpy2
print('Primeros valores lista', suma1[0], suma1[1], suma1[2], suma1[3])
print('Primeros valores numPy', suma2[0], suma2[1], suma2[2], suma2[3])

Primeros valores lista 0 2 4 6
Primeros valores numPy 0 2 4 6


In [ ]:
### Velocidad
import time
tamanioLista = 1000000
lista1 = range(tamanioLista)
lista2 = range(tamanioLista)
numpy1 = np.arange(tamanioLista)
numpy2 = np.arange(tamanioLista)
inicio1 = time.time()
suma1 = [x + y for x, y in zip(lista1, lista2)]
final1 = time.time()
inicio2 = time.time()
suma2 = numpy1 + numpy2
final2 = time.time()
print('Tiempo utilizando listas', (final1 - inicio1) * 1000, 'seg.')
print('Tiempo utilizando numPy', (final2 - inicio2) * 1000, 'seg.')

Tiempo utilizando listas 261.3973617553711 seg.
Tiempo utilizando numPy 3.191709518432617 seg.


In [ ]:
# Especificar el tipo de dato
n = np.array([[0,1],[5,6],[8,9]], dtype = np.float64)
n

array([[0., 1.],
       [5., 6.],
       [8., 9.]])

In [ ]:
# Crear matrices inicializadas

### Con 1
unos = np.ones(5)
print('Unidimensional', unos)
unos = np.ones((2,3))
print('N-dimensional', unos)

Unidimensional [1. 1. 1. 1. 1.]
N-dimensional [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
### Con 0
ceros = np.zeros((2,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
### Con números random
random = np.random.random((2,3))
random

array([[0.01266356, 0.13267638, 0.66034355],
       [0.46916092, 0.32801647, 0.57645675]])

In [ ]:
### Con números random enteros desde/hasta
random = np.random.randint(1,10,size=(2,3))
random

array([[9, 7, 5],
       [9, 3, 3]])

In [ ]:
### Con un determinado valor
valor = np.full((2,3),23)
valor

array([[23, 23, 23],
       [23, 23, 23]])

In [ ]:
### Con valores espaciados uniformemente
espaciados = np.arange(0,50,10)
espaciados


array([ 0, 10, 20, 30, 40])

In [ ]:
### Matriz identidad
identidad = np.eye(3,3)
identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Conocer la dimension de una matriz
m1 = np.ones(3)
print('Unidimensional:', m1.ndim)
m2 = np.ones((2,3))
print('Bidimensional:', m2.ndim)
m4 = np.ones((2,3,8,4))
print('N-dimensionanl:', m4.ndim)

Unidimensional: 1
Bidimensional: 2
N-dimensionanl: 4


In [ ]:
# Conocer el tipo de datos de una matriz
m1 = np.ones(3)
print('default:', m1.dtype)
m2 = np.ones(3, dtype=np.int32)
print('int:', m2.dtype)


default: float64
int: int32


In [ ]:
# Conocer el tamaño de una matriz
m1 = np.ones(3)
print('3 posiciones:', m1.size)
m2 = np.ones((3,4))
print('12 posiciones:', m2.size)

3 posiciones: 3
12 posiciones: 12


In [ ]:
# Conocer la forma de una matriz
m = np.ones((2,3))
np.shape(m)

(2, 3)

In [ ]:
# Cambio de tamaño y forma de la matriz
m1 = np.array([[1,2],[3,4],[5,6]])
print('3x2', m1)
m2 = m1.reshape(2,3)
print('2x3', m2)

3x2 [[1 2]
 [3 4]
 [5 6]]
2x3 [[1 2 3]
 [4 5 6]]


In [ ]:
# Transponer una matriz
m1 = np.array([[1,2],[3,4],[5,6]])
print('3x2', m1)
m2 = m1.transpose()
print('2x3', m2)

3x2 [[1 2]
 [3 4]
 [5 6]]
2x3 [[1 3 5]
 [2 4 6]]


In [ ]:
# Encontrar un elemento de una matriz
m = np.array([[1,2,3,4],[4,5,6,7],[8,9,0,11]])
m[1,2]

6

In [ ]:
# Encontrar varios elementos de una matriz
m = np.array([[1,2,3,4],[4,5,6,7],[8,9,0,11]])
m[0:,2]

array([3, 6, 0])

In [ ]:
# Operaciones matemáticas y estadísticas sobre una matriz
m = np.array([11,22,44])
print('Suma:', m.sum())
print('Mínimo:', m.min())
print('Máximo:', m.max())
print('Promedio:', m.mean())
print('Desvío estandar:', m.std())
print('Raices cuadradas:', np.sqrt(m))

Suma: 77
Mínimo: 11
Máximo: 44
Promedio: 25.666666666666668
Desvío estandar: 13.719410418171119
Raices cuadradas: [3.31662479 4.69041576 6.63324958]


In [ ]:
# Operaciones matemáticas entre matrices (punto a punto)
m1 = np.array([1,2,4])
m2 = np.array([1,2,4])
print('Suma:', m1+m2)
print('Resta:', m2-m1)
print('Multiplicación:', m2*m1)
print('División:', m2/m1)

Suma: [2 4 8]
Resta: [0 0 0]
Multiplicación: [ 1  4 16]
División: [1. 1. 1.]


In [ ]:
# Multiplicar matrices 
m1 = np.random.randint(1,10,size = (3,3))
m2 = np.random.randint(1,10,size = (3,2))
print('m1:',m1)
print('m2',m2)
np.matmul(m1,m2)

m1: [[1 6 3]
 [4 9 4]
 [3 2 1]]
m2 [[6 7]
 [5 4]
 [4 7]]


array([[48, 52],
       [85, 92],
       [32, 36]])